spring:
  application:
    name: langgomsport
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/langgomsport
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  flyway:
    enabled: false
    locations: classpath:db/migrations
    baseline-on-migrate: true
    validate-on-migrate: true
