spring:
  application:
    name: langgomsport
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3309/langgomsport?createDatabaseIfNotExist=true
    username: admin
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  flyway:
    enabled: false
    locations: classpath:db/migrations
    baseline-on-migrate: false
    validate-on-migrate: false

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:redis}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      repositories:
        enabled: false
